### ISSUE TITLE
libkevlar relies on OpenSSL (libcrypto)

### ISSUE THREAD

**Issue by macmade** [DevMate/DevMateKit#22] opened 2016-08-16 08:08 UTC
In order to link with `libkevlar`, we used to link with the system's `libcrypto`, as `libkevlar` internally uses some OpenSSL symbols.

As of Xcode 8, Apple now prevents linking with the system's OpenSSL libraries, for security reasons.
The used symbols have been deprecated since a long time.

So the only way to make this work is to build a custom version of OpenSSL and ship it with the product.
This isn't really a good solution.

`libkevlar` should use modern crypto functions provided by Apple frameworks, instead of relying on OpenSSL.

**Comment by dimaty** [comment] 2016-08-16 10:33
Yes, we know about this problem and now we're working on it's update. Can you close this issue as a duplicate of the the other one (https://github.com/DevMate/DevMateKit/issues/20)?

**Comment by macmade** [comment] 2016-08-16 14:15
Thank you : )

**Closed** 2016-08-16 14:15 UTC
